### PR TITLE
Discovery Bluetooth (not tested) and the ALL Printers

### PR DESCRIPTION
**Pull request by brasizza**
1.  Upgraded the .jar and so files to the newest that i found.
2. Implemented the Bluetooth and all devices discovery ( I don't have any bluetooth but it's the same method)
3. Refact the onDiscoveryPrinter , now there is only one method to find printers and i put the device in parameter
4.  Fix some null errors in example project

Thanks for your package it's SIMPLY AWESOME!

### CODE REVIEW

**Comment by mrtungdev** [comment]
wow, honestly this package I not maintenance about 1 year but you make me want to improve that. Thanks so much @brasizza , I appreciated that.

**Comment by TrentStarky** [comment]
@brasizza do you have any plans to reopen this PR? These changes are great and would be very useful to the package.

**Comment by brasizza** [comment]
i have but there is a lot of breakchange that i need to arrange it.
One thing that i fix is to use this package into x86 android devices as well

**Comment by TrentStarky** [comment]
No worries, if there's anything you'd like help with / tested I am available :)

**Comment by brasizza** [comment]
@TrentStarky  try mine 
if its ok i can do a pull request again
https://github.com/brasizza/flutter_epson_epos

**Pull request closed without merging**
